/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#4edea3",
        "inverse-on-surface": "#2e3036",
        "on-surface-variant": "#bcc9cd",
        "on-secondary": "#003824",
        "on-tertiary-fixed": "#07006c",
        "on-secondary-fixed": "#002113",
        "on-background": "#e1e2ea",
        "surface-variant": "#32353b",
        "surface": "#111319",
        "tertiary-fixed-dim": "#c0c1ff",
        "primary": "#4cd7f6",
        "surface-container-high": "#272a30",
        "surface-dim": "#111319",
        "on-surface": "#e1e2ea",
        "surface-bright": "#36393f",
        "primary-container": "#06b6d4",
        "on-primary-fixed": "#001f26",
        "primary-fixed-dim": "#4cd7f6",
        "outline": "#869397",
        "tertiary-container": "#9a9dff",
        "on-tertiary-container": "#211cb4",
        "on-primary-fixed-variant": "#004e5c",
        "surface-container": "#1d2025",
        "secondary-container": "#00a572",
        "tertiary": "#c0c1ff",
        "surface-container-lowest": "#0b0e13",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "background": "#111319",
        "on-secondary-container": "#00311f",
        "on-primary": "#003640",
        "on-tertiary": "#1000a9",
        "on-secondary-fixed-variant": "#005236",
        "on-error": "#690005",
        "primary-fixed": "#acedff",
        "inverse-surface": "#e1e2ea",
        "surface-tint": "#4cd7f6",
        "secondary": "#4edea3",
        "secondary-fixed": "#6ffbbe",
        "on-primary-container": "#00424f",
        "inverse-primary": "#00687a",
        "surface-container-low": "#191c21",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-error-container": "#ffdad6",
        "outline-variant": "#3d494c",
        "surface-container-highest": "#32353b"
      },
      spacing: {
        "space-md": "0.75rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin-mobile": "0.75rem",
        "gutter-dense": "0.5rem",
        "space-lg": "1rem",
        "margin": "1.5rem",
        "gutter": "1rem",
        "space-xl": "1.5rem"
      },
      fontFamily: {
        "label-code": ["JetBrains Mono", "monospace"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "display-hero": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-mono-sm": ["JetBrains Mono", "monospace"],
        "display-hero-mobile": ["Geist", "sans-serif"]
      },
    },
  },
  plugins: [],
};
